/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/t1ADdq1UL3m
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent } from "@/components/ui/dropdown-menu"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"
import { useTranslation } from 'react-i18next';

export function SearchBar() {
  const { t } = useTranslation()
  return (
    <div className="w-full max-w-7xl mx-auto p-4">
      <div className="text-center mb-4">
        <h1 className="text-3xl font-bold">{t('search-bar.1')}</h1>
      </div>
      <div className="bg-white shadow-md rounded-xl">
        <Tabs defaultValue="buy">
          <TabsList className="flex space-x-2">
            <TabsTrigger value="buy">{t('search-bar.2')}</TabsTrigger>
            <TabsTrigger value="rent">{t('search-bar.3')}</TabsTrigger>
            <TabsTrigger value="daily">{t('search-bar.4')}</TabsTrigger>
          </TabsList>
        </Tabs>
        <div className="p-4">
          <div className="flex flex-wrap gap-4">
            <Select>
              <SelectTrigger className="w-full sm:w-auto">
                <SelectValue placeholder="Квартиру" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="new">{t('search-bar.5')}</SelectItem>
              </SelectContent>
            </Select>
            <Select>
              <SelectTrigger className="w-full sm:w-auto">
                <SelectValue placeholder="1-4 комн." />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">{t('search-bar.6')}</SelectItem>
                <SelectItem value="2">{t('search-bar.7')}</SelectItem>
                <SelectItem value="3">{t('search-bar.8')}</SelectItem>
                <SelectItem value="4">{t('search-bar.9')}</SelectItem>
              </SelectContent>
            </Select>
            <DropdownMenu>
              <DropdownMenuTrigger className="w-full sm:w-auto">
                <div className="flex items-center justify-between">
                  <span>{t('search-bar.10')}</span>
                  <ChevronDownIcon className="h-4 w-4" />
                </div>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="w-[300px]">
                <div className="grid gap-4 p-4">
                  <div className="grid grid-cols-2 gap-2">
                    <Input type="number" placeholder="От" className="w-full" />
                    <Input type="number" placeholder="До" className="w-full" />
                  </div>
                </div>
              </DropdownMenuContent>
            </DropdownMenu>
            <Input type="text" placeholder="Город, улица, квартиры для большой семьи" className="w-full flex-1" />
            
          </div>
        </div>
      </div>
            <div className=" text-right mb-4 p-4">
            {/* <Button variant="outline" className="w-full sm:w-auto mx-2">
              Показать на карте
            </Button> */}
            <Button className="px-4 py-2 w-full sm:w-auto mx-2 bg-[#ff851a] hover:bg-[#ce792e]">{t('search-bar.11')}</Button>
            </div>
    </div>
  )
}

function ChevronDownIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}
